require(script.Shops)
require(script.TutorialUI)
require(script.Combat)
require(script.MainUI)
require(script.Displays)
require(script.Missions)
require(script.BuffsUI)
require(script.CodesUI)
require(script.SettingsUI)
require(script.FixRichText)
require(script.Inventories)
require(script.ChestTimerUI)
require(script.BillboardShops)
require(script.NotificationUI)
require(script.GiftUI)
require(script.RebirthUI)

return 0
