return {
	Strength = 1,
	Fear = 0,
	Kills = 0,
	Rebirths = 0,

	Luck = 0,
	Gems = 0,
	Rank = 1,

	PetFearMultiplier = 0,

	CurrentPetCount = 0,
	MaxPetCount = 30,

	CurrentPetEquipCount = 0,
	MaxPetEquipCount = 3,

	AwardedGamepasses = {},
	FoundPets = {},
	OwnedPets = {},
	EquippedPets = {},
	OwnedWeapons = {
		["Fists"] = true,
	},
	EquippedWeapon = "Fists",

	LogInCount = 0,
	HoursPlayed = 0,
}
