name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: Roblox/setup-foreman@v1
      name: Install Foreman
      with:
        token: ${{ SECRETS.GITHUB_TOKEN }}
      
    - name: Lint
      run: |
        selene ./src
        selene ./src --pattern **/*.luau

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JohnnyMorganz/stylua-action@v1
      with:
        token: ${{ SECRETS.GITHUB_TOKEN }}
        version: "0.15.1"
        args: --check ./src
